spring:
  application:
    name: Inventory Service
  data:
    mongodb:
      uri: mongodb+srv://letniki:admin@cluster0.y379y.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: products-db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-3ye8hk3rxi1gafds.us.auth0.com/
  logging:
    level:
      sun:
        rmi:
          transport:
            tcp: OFF
  server:
    port: 8082