spring:
  application:
    name: Inventory Service
  data:
    mongodb:
      uri: mongodb+srv://letniki:admin@cluster0.y379y.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: products-db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-3ye8hk3rxi1gafds.us.auth0.com/
  cloud:
    function:
      definition: product-deleted
    stream:
      bindings:
        product-deleted-in-0:
          destination: product-deleted-events
          group: inventory-service
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
logging:
  level:
    sun:
      rmi:
        transport:
          tcp: OFF
server:
  port: 8081